# Config file for using Skaffold in local development
# Custom builder so we can use dependencies.paths (only supported for custom).
# Both images use repo root (.) as build context. Only listed paths trigger rebuilds.

apiVersion: skaffold/v4beta13
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: 1ntellijosh/bigtix-auth-srv
      context: .
      custom:
        buildCommand: docker build -f auth-srv/deploy/docker/dev.Dockerfile -t $IMAGE $BUILD_CONTEXT
        dependencies:
          paths:
            - auth-srv/**/*
            - packages/*/dist/**/*
      sync:
        manual:
          - src: 'auth-srv/src/**/*.ts'
            dest: src
            strip: 'auth-srv/src/'
    - image: 1ntellijosh/bigtix-tickets-srv
      context: .
      custom:
        buildCommand: docker build -f tickets-srv/deploy/docker/dev.Dockerfile -t $IMAGE $BUILD_CONTEXT
        dependencies:
          paths:
            - tickets-srv/**/*
            - packages/*/dist/**/*
      sync:
        manual:
          - src: 'tickets-srv/src/**/*.ts'
            dest: src
            strip: 'tickets-srv/src/'
    - image: 1ntellijosh/bigtix-orders-srv
      context: .
      custom:
        buildCommand: docker build -f orders-srv/deploy/docker/dev.Dockerfile -t $IMAGE $BUILD_CONTEXT
        dependencies:
          paths:
            - orders-srv/**/*
            - packages/*/dist/**/*
      sync:
        manual:
          - src: 'orders-srv/src/**/*.ts'
            dest: src
            strip: 'orders-srv/src/'
    - image: 1ntellijosh/bigtix-payments-srv
      context: .
      custom:
        buildCommand: docker build -f payments-srv/deploy/docker/dev.Dockerfile -t $IMAGE $BUILD_CONTEXT
        dependencies:
          paths:
            - payments-srv/**/*
            - packages/*/dist/**/*
      sync:
        manual:
          - src: 'payments-srv/src/**/*.ts'
            dest: src
            strip: 'payments-srv/src/'
    - image: 1ntellijosh/bigtix-client-app
      context: .
      custom:
        buildCommand: docker build -f client/deploy/docker/dev.Dockerfile -t $IMAGE $BUILD_CONTEXT
        dependencies:
          paths:
            - client/**/*
            - packages/*/dist/**/*
      sync:
        manual:
          - src: 'client/**/*'
            dest: .
            strip: 'client/'
manifests:
  rawYaml:
    - ./ops/k8s/deployments/auth-depl.yml
    - ./ops/k8s/deployments/auth-mongo-depl.yml
    - ./ops/k8s/deployments/client-depl.yml
    - ./ops/k8s/deployments/tickets-depl.yml
    - ./ops/k8s/deployments/tickets-mongo-depl.yml
    - ./ops/k8s/deployments/orders-depl.yml
    - ./ops/k8s/deployments/orders-mongo-depl.yml
    - ./ops/k8s/deployments/payments-depl.yml
    - ./ops/k8s/deployments/payments-mongo-depl.yml
    - ./ops/k8s/ingresses/ingress-srv.yml
    # RabbitMQ is applied by setup-cluster.yml only to speed up cluster setup;
    # including it here ALSO would break skaffold sync
deploy:
  kubectl: {}
