apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./ops/k8s/**/*
build:
  local:
    push: false
  artifacts:
    - image: 1ntellijosh/bigtix-auth-srv
      context: auth-srv
      docker:
        dockerfile: deploy/docker/dev.Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
